# Generated by Django 5.2.17 on 2026-09-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='Internal path to open when the notification is clicked (defaults to the dashboard).', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('new_donation', 'New donation'), ('claimed', 'Donation claimed'), ('ready', 'Ready for pickup'), ('picked_up', 'Picked up'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('update', 'Status update'), ('offer', 'Offer'), ('offer_lapsed', 'Offer lapsed'), ('released', 'Released'), ('expiring', 'Expiring soon'), ('expired', 'Expired'), ('opened', 'Open to all'), ('approval', 'Account approval')], default='update', max_length=20),
        ),
    ]
