# Generated by Django 5.2.17 on 2026-09-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_notification_link_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('new_donation', 'New donation'), ('claimed', 'Donation claimed'), ('ready', 'Ready for pickup'), ('picked_up', 'Picked up'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('update', 'Status update'), ('offer', 'Offer'), ('offer_lapsed', 'Offer lapsed'), ('released', 'Released'), ('expiring', 'Expiring soon'), ('expired', 'Expired'), ('opened', 'Open to all'), ('approval', 'Account approval'), ('issue', 'Reported issue')], default='update', max_length=20),
        ),
    ]
