# Generated by Django 6.1.2 on 2026-10-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0003_alter_notification_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("new_donation", "New donation"),
                    ("claimed", "Donation claimed"),
                    ("ready", "Ready for pickup"),
                    ("picked_up", "Picked up"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("update", "Status update"),
                    ("offer", "Offer"),
                    ("offer_lapsed", "Offer lapsed"),
                    ("released", "Released"),
                    ("expiring", "Expiring soon"),
                    ("expired", "Expired"),
                    ("opened", "Open to all"),
                    ("approval", "Account approval"),
                    ("issue", "Reported issue"),
                    ("live_tracking", "Live tracking (coming soon)"),
                ],
                default="update",
                max_length=20,
            ),
        ),
    ]
