# Generated by Django 6.1.2 on 2026-10-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0004_add_live_tracking_notification_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_broadcast",
            field=models.BooleanField(
                default=False,
                help_text="Sent to every account at once by an Admin, rather than a direct one-to-one message.",
            ),
        ),
    ]
