# Generated by Django 5.2.17 on 2026-09-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_approve_existing_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Also email me important updates (offers, approvals, cancellations).'),
        ),
    ]
