# Generated by Django 5.2.17 on 2026-09-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_email_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DONOR', 'Donor'), ('RECIPIENT', 'Recipient'), ('DRIVER', 'Driver'), ('ADMIN', 'Admin'), ('AUDITOR', 'Auditor')], default='DONOR', max_length=20),
        ),
    ]
