# Generated by Django 5.2.17 on 2026-09-28 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('listed', 'Listed'), ('offered', 'Offered to nearby partners'), ('declined', 'Offer declined'), ('timed_out', 'Offer timed out'), ('opened', 'Opened to all eligible partners'), ('claimed', 'Claimed by a pantry'), ('released', 'Claim released'), ('picked_up', 'Accepted for pickup'), ('withdrawn', 'Driver withdrew'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], max_length=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('RECIPIENT', 'Recipient'), ('DRIVER', 'Driver')], max_length=10)),
                ('wave', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('offered', 'Offered'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('timed_out', 'Timed out'), ('withdrawn', 'Withdrawn')], default='offered', max_length=10)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['donation_id', 'wave', 'distance_km'],
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='cancel_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='donation',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('unavailable', 'Food is no longer available'), ('safety', 'Quality or food-safety concern'), ('mistake', 'Listed by mistake'), ('no_pickup', 'Pickup is no longer possible'), ('elsewhere', 'Found another recipient'), ('cant_collect', "We can't receive it in time"), ('no_storage', 'No storage space available'), ('not_needed', 'No longer needed'), ('vehicle', 'Vehicle unavailable'), ('too_far', 'Too far for me'), ('schedule', 'Schedule conflict'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='driver_pool_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='expiry_warning_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='pickup_area',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='donation',
            name='recipient_pool_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('In transit', 'In transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Expired', 'Expired')], default='Pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status', 'expires_at'], name='donations_d_status_608e66_idx'),
        ),
        migrations.AddField(
            model_name='donationevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donationevent',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='donations.donation'),
        ),
        migrations.AddField(
            model_name='offer',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='donations.donation'),
        ),
        migrations.AddField(
            model_name='offer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['status', 'expires_at'], name='donations_o_status_7fd085_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['user', 'status'], name='donations_o_user_id_6dc88b_idx'),
        ),
    ]
