# Generated by Django 5.2.17 on 2026-09-28 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donationevent_offer_donation_cancel_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='allergen_note',
            field=models.CharField(blank=True, help_text='e.g. contains nuts, gluten, dairy', max_length=150),
        ),
        migrations.AddField(
            model_name='donation',
            name='date_type',
            field=models.CharField(choices=[('use_by', 'Use by'), ('best_before', 'Best before')], default='use_by', max_length=12),
        ),
        migrations.AddField(
            model_name='donation',
            name='food_category',
            field=models.CharField(choices=[('produce', 'Fresh produce'), ('bakery', 'Bakery'), ('dairy', 'Dairy & eggs'), ('meat_fish', 'Meat & fish'), ('prepared', 'Prepared meals'), ('packaged', 'Packaged / pantry'), ('other', 'Other')], default='other', max_length=12),
        ),
        migrations.AddField(
            model_name='donation',
            name='safety_confirmed',
            field=models.BooleanField(default=False, help_text='Donor confirmed the food is safe, correctly stored and within its date.'),
        ),
        migrations.AddField(
            model_name='donation',
            name='storage',
            field=models.CharField(choices=[('ambient', 'Room temperature'), ('chilled', 'Keep chilled'), ('frozen', 'Keep frozen')], default='ambient', max_length=8),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='1 (poor) to 5 (excellent)')),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('is_issue', models.BooleanField(default=False, help_text='Something went wrong and an admin should look.')),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to=settings.AUTH_USER_MODEL)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='donations.donation')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('donation', 'author'), name='one_feedback_per_person')],
            },
        ),
    ]
