# Generated by Django 5.2.17 on 2026-10-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donation_allergen_note_donation_date_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='photo',
            field=models.ImageField(blank=True, help_text="A real photo of the food - shown on the listing and, if it's live, on the Home page showcase.", null=True, upload_to='donation_photos/'),
        ),
    ]
