from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.db.models import Count, Q
from django.http import JsonResponse
from django.urls import reverse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from django.views.decorators.http import require_POST

from accounts.decorators import admin_required
from . import services
from .forms import BroadcastForm, MessageForm, NewMessageForm
from .models import Message, Notification

User = get_user_model()


def _conversations(user):
    """One row per person the user has chatted with: latest message + unread count."""
    recent = (
        Message.objects.filter(Q(sender=user) | Q(recipient=user))
        .select_related("sender", "recipient")
        .order_by("-created_at")[:500]
    )
    unread = dict(
        Message.objects.filter(recipient=user, read_at__isnull=True)
        .order_by().values_list("sender").annotate(n=Count("id"))
    )
    rows, seen = [], set()
    for msg in recent:
        other = msg.recipient if msg.sender_id == user.pk else msg.sender
        if other.pk in seen:
            continue
        seen.add(other.pk)
        rows.append({"other": other, "last": msg, "unread": unread.get(other.pk, 0)})
    return rows


@login_required
def inbox_home(request):
    return render(request, "inbox/inbox.html", {
        "notifications": request.user.notifications.select_related("donation")[:40],
        "conversations": _conversations(request.user),
    })


@login_required
def conversation(request, user_id):
    other = get_object_or_404(User, pk=user_id, is_active=True)
    if other.pk == request.user.pk:
        return redirect("inbox:home")
    # Only open a thread between people who are actually allowed to message each
    # other - an Admin, or someone linked through the donation process - even if a
    # broadcast or an earlier message means a thread technically already exists.
    if not services.can_message(request.user, other):
        raise PermissionDenied("You can only message someone you're involved with on a donation.")

    if request.method == "POST":
        form = MessageForm(request.POST)
        if form.is_valid():
            Message.objects.create(sender=request.user, recipient=other, body=form.cleaned_data["body"])
            return redirect("inbox:conversation", user_id=other.pk)
    else:
        form = MessageForm()

    thread = list(
        Message.objects.filter(
            Q(sender=request.user, recipient=other) | Q(sender=other, recipient=request.user)
        ).order_by("-created_at")[:200]
    )[::-1]
    # Everything they sent me is now read (thread above still remembers what was new).
    Message.objects.filter(sender=other, recipient=request.user, read_at__isnull=True).update(
        read_at=timezone.now()
    )
    return render(request, "inbox/conversation.html", {"other": other, "thread": thread, "form": form})


@admin_required
def broadcast(request):
    """Admin-only: send one message to every account at once. No other role can do this -
    everyone else may only message someone they're linked with on a donation."""
    form = BroadcastForm(request.POST or None)
    sent = None
    if request.method == "POST" and form.is_valid():
        sent = services.broadcast_message(request.user, form.cleaned_data["body"])
        form = BroadcastForm()
    return render(request, "inbox/broadcast.html", {"form": form, "sent": sent})


@login_required
def new_message(request):
    initial = {}
    to = request.GET.get("to", "")
    if to.isdigit():
        initial["recipient"] = int(to)
    form = NewMessageForm(request.POST or None, user=request.user, initial=initial)
    if request.method == "POST" and form.is_valid():
        recipient = form.cleaned_data["recipient"]
        Message.objects.create(sender=request.user, recipient=recipient, body=form.cleaned_data["body"])
        return redirect("inbox:conversation", user_id=recipient.pk)
    return render(request, "inbox/new_message.html", {"form": form})


@login_required
def notification_open(request, pk):
    """Click-through from the inbox: mark the notification read, then go to the dashboard."""
    notification = get_object_or_404(Notification, pk=pk, user=request.user)
    if notification.read_at is None:
        notification.read_at = timezone.now()
        notification.save(update_fields=["read_at"])
    # Links are generated by the app, but never redirect anywhere off-site.
    if notification.link and notification.link.startswith("/") and not notification.link.startswith("//"):
        return redirect(notification.link)
    return redirect("accounts:dashboard")


@login_required
@require_POST
def mark_all_read(request):
    Notification.objects.filter(user=request.user, read_at__isnull=True).update(read_at=timezone.now())
    return redirect("inbox:home")


def unread_json(request):
    """Polled by the nav badge (counts) and the toast popup (the newest unread items
    themselves, so the page can tell what's genuinely new since the last poll). Every
    query here is scoped to request.user - a person only ever sees their own unread
    items, never another donor's, recipient's, driver's or admin's."""
    if not request.user.is_authenticated:
        return JsonResponse({"error": "auth"}, status=401)
    notif_qs = Notification.objects.filter(user=request.user, read_at__isnull=True).order_by("-created_at")
    msg_qs = Message.objects.filter(recipient=request.user, read_at__isnull=True).select_related("sender").order_by("-created_at")
    n = notif_qs.count()
    m = msg_qs.count()
    recent_notifications = [
        {
            "id": x.pk, "text": x.text,
            "url": reverse("inbox:notification_open", args=[x.pk]),
            "created_at": x.created_at.isoformat(),
        }
        for x in notif_qs[:5]
    ]
    recent_messages = [
        {
            "id": x.pk, "text": f"{x.sender.display_name}: {x.body[:80]}",
            "url": reverse("inbox:conversation", args=[x.sender_id]),
            "created_at": x.created_at.isoformat(),
        }
        for x in msg_qs[:5]
    ]
    return JsonResponse({
        "notifications": n, "messages": m, "total": n + m,
        "recent_notifications": recent_notifications, "recent_messages": recent_messages,
    })
